### PR TITLE
fix: prevent bullet from killing shooter.

### LINKED ISSUE #715: Don't Let The Musket Bullet Kill the Player That Shot It
This can happen if you turn around very quickly.

We can fix this by setting the owner of the damage region for the bullet to the player that shot the gun.

### PR DESCRIPTION
**Pull request by iwek7**
This fixes #715. Issue suggested that what should be done is adding owner to damage region (as is done in case of sword), however it seems that bullet does not use those regions so I simply add entity marker to bullet object and filter out all collisions with this entity.

### CODE REVIEW

File: core/src/elements/musket.rs [hunk 1]
```diff
@@ -221,6 +221,7 @@ fn update(
                             bullets.insert(
                                 ent,
                                 Bullet {
+                                    owner: player.clone(),
```
Comment (zicklag) [inline core/src/elements/musket.rs:224]: Can you remove this `clone()`.

**Review by zicklag — COMMENTED** [review]
Awesome, thanks! Just one clippy lint to fix.

And please run `cargo fmt`, too.
